import type { Metadata } from "next";
import { Inter,Adamina,Syne } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layout/Footer";
import Navbar from "@/components/layout/navbar";
import  {syne,inter, dmsans} from "@/app/font"



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/images/favicon/favicon.ico',
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <body className={`${inter.className} ${syne.variable} ${dmsans.variable}` }>
        <Navbar/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
